FROM mariadb:10.6

ENV MYSQL_ROOT_PASSWORD=123

COPY /Users/yoo/Desktop/DockerVolume /var/lib/mysql

EXPOSE 3301

CMD ["mysqld"]


## docker run -d -p 3301:3301 -e MYSQL_ROOT_PASSWORD=123 -v /Users/yoo/Desktop/DockerVolume:/var/lib/mysql --network yooNet --name db mariadb:10.6
